# Generated by Django 3.0.3 on 2020-05-18 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='name',
            field=models.CharField(default='kokoko', max_length=30),
            preserve_default=False,
        ),
    ]
