# Generated by Django 3.0.6 on 2020-05-21 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_expense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
