# Generated by Django 3.0.6 on 2020-05-21 08:54

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0005_expense_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=500)),
                ('amount', models.FloatField(validators=[django.core.validators.MaxValueValidator(999999999999999), django.core.validators.MinValueValidator(0)])),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to=settings.AUTH_USER_MODEL)),
                ('balance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='finance.Balance')),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='payment', to='finance.Expense')),
            ],
        ),
    ]
