# Generated by Django 3.0.6 on 2020-05-21 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='amount',
        ),
    ]
