# Generated by Django 3.0.6 on 2020-05-21 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_remove_expense_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='description',
            field=models.TextField(),
        ),
    ]
