# Generated by Django 3.0.6 on 2020-05-21 10:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_auto_20200521_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='payment',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
