# Generated by Django 3.0.6 on 2020-05-21 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_auto_20200521_1323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='time',
            new_name='datetime',
        ),
    ]
