# Generated by Django 3.0.6 on 2020-05-22 15:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0010_auto_20200521_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='expense',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payment',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payment',
            name='balance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.Balance'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='expense',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='finance.Expense'),
        ),
    ]
