# Generated by Django 3.0.6 on 2020-05-22 15:34

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0011_auto_20200522_1814'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('amount', models.FloatField(validators=[django.core.validators.MaxValueValidator(999999999999999), django.core.validators.MinValueValidator(0)])),
                ('coef', models.FloatField(validators=[django.core.validators.MaxValueValidator(999999999999999), django.core.validators.MinValueValidator(0)])),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('from_balance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_balance', to='finance.Balance')),
                ('to_balance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_balance', to='finance.Balance')),
            ],
        ),
    ]
