# Generated by Django 3.0.6 on 2020-06-02 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0014_auto_20200522_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='name',
            field=models.CharField(default='migrate', max_length=30),
            preserve_default=False,
        ),
    ]
