# Generated by Django 3.0.6 on 2020-06-02 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0015_payment_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='title',
        ),
    ]
