# Generated by Django 3.0.3 on 2020-05-15 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_profile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(help_text='Please use the following format: <em>YYYY-MM-DD</em>.', null=True),
        ),
    ]
