# Generated by Django 3.0.6 on 2020-05-20 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20200515_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default\\profile_image.jpg', upload_to='profile_pics'),
        ),
    ]
